package com.chatapp;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;

public class MessageTest {

    private static Message firstMessage  = new Message();
    private static Message secondMessage = new Message();
    private static Message utilityMessage = new Message();

    @BeforeAll
    public static void initializeTests() {
        firstMessage.setRecipientCell("+27718693002");
        firstMessage.setSenderCell("+271234567");
        firstMessage.setMessageBody("Hi Mike, can you join us for dinner tonight?");
        secondMessage.setRecipientCell("08575975889");
        secondMessage.setSenderCell("+271234567");
        secondMessage.setMessageBody("Hi Keegan, did you receive the payment?");

        utilityMessage.initializeMessage(firstMessage);

        utilityMessage.numberOfMessagesSent = 1; // this is usually updated when sending a message, but to use our objects for testing purposes, we updated it here to simulate a 2nd message
        utilityMessage.initializeMessage(secondMessage);

    }

    @Test
    @Order(1)
    public void checkSendMessage() {

        assertEquals("Message successfully sent.", utilityMessage.sendMessage(firstMessage, 1));
        assertEquals("Press 0 to delete the message.\n", utilityMessage.sendMessage(firstMessage, 2));
        assertEquals("Message successfully stored.\n", utilityMessage.sendMessage(firstMessage, 3));
        assertEquals("Message successfully sent.", utilityMessage.sendMessage(secondMessage, 1));
        assertEquals("Press 0 to delete the message.\n", utilityMessage.sendMessage(secondMessage, 2));
        assertEquals("Message successfully stored.\n", utilityMessage.sendMessage(secondMessage, 3));

    }

    @Test
    @Order(2)
    public void checkMessageHash() {
        // not sure what loop test the requirement was referring to, we only have 2 messages and their Hashes are autogenerated as per another requirement...
        assertEquals(String.valueOf(firstMessage.getMessageID()).substring(0, 2) + ":0:HITONIGHT", firstMessage.messageHash);
        assertNotEquals(String.valueOf(firstMessage.getMessageID()).substring(0, 2) + ":1:HITONIGHT", firstMessage.messageHash);
        assertEquals(String.valueOf(secondMessage.getMessageID()).substring(0, 2) + ":1:HIPAYMENT", secondMessage.messageHash);
        assertNotEquals(String.valueOf(secondMessage.getMessageID()).substring(0, 2) + ":0:HIPAYMENT", secondMessage.messageHash);

    }


    @Test
    @Order(3)
    public void checkMessageID() {
        assertNotNull(firstMessage.createMessageID(utilityMessage));
        assertNotNull(secondMessage.createMessageID(utilityMessage));
    }

    @Test
    @Order(4)
    public void checkRecipientCell() {
        // could easily reuse the login test logic here, but its industry practice to not overlap tests, even if they're similar
        // Message tests are for message classes, this allows us to add specific test criteria in future without affecting login tests
        assertEquals("Cell phone number successfully captured.\n", utilityMessage.checkRecipientCell(firstMessage.getRecipientCell()));
        assertNotEquals("Cell phone number incorrectly formatted or does not contain an international code. Please correct the number and try again.\n", utilityMessage.checkRecipientCell(firstMessage.getRecipientCell()));
        assertEquals("Cell phone number incorrectly formatted or does not contain an international code. Please correct the number and try again.\n", utilityMessage.checkRecipientCell(secondMessage.getRecipientCell()));
        assertNotEquals("Cell phone number successfully captured.\n", utilityMessage.checkRecipientCell(secondMessage.getRecipientCell()));

    }

    @Test
    @Order(5)
    public void checkMessageBody() {
        assertTrue(utilityMessage.checkMessageBody(firstMessage.getMessageBody()));
        assertTrue(utilityMessage.checkMessageBody(secondMessage.getMessageBody()));
        // more than 250 characters...
        assertFalse(firstMessage.checkMessageBody("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
        assertFalse(firstMessage.checkMessageBody("Lots and lots of words, an extreme amount of words. Loads and loads and loads and loads of words. Seriously a lot of words, an unimaginable amount of words. a whole lot of words, really so much words its hard to believe how many words are here. So many words."));
    }

}
