package com.chatapp;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;

public class MessageTest {

    private static Message firstMessage  = new Message();
    private static Message secondMessage = new Message();

    @BeforeAll
    public static void initializeTests() {
        firstMessage.setRecipientCell("+27718693002");
        firstMessage.setSenderCell("+271234567");
        firstMessage.setMessageBody("Hi Mike, can you join us for dinner tonight?");
        secondMessage.setRecipientCell("08575975889");
        secondMessage.setSenderCell("+271234567");
        secondMessage.setMessageBody("Hi Keegan, did you receive the payment?");

        // pass in the same object references, will update fields via pass-by-reference
        firstMessage.initializeMessage(firstMessage);
        secondMessage.initializeMessage(secondMessage);

    }


    @Test
    public void checkMessageID() {
        message.checkMessageID();

    }

    @Test
    public void checkRecipientCell() {
        // could easily reuse the login test logic here, but its industry practice to not overlap tests, even if they're similar
        // Message tests are for message classes, this allows us to add specific test criteria in future without affecting login tests
        assertEquals("Cell phone number successfully captured.\n", firstMessage.checkRecipientCell(firstMessage.getRecipientCell()));
        assertNotEquals("Cell phone number incorrectly formatted or does not contain an international code. Please correct the number and try again.\n", firstMessage.checkRecipientCell(firstMessage.getRecipientCell()));
        assertEquals("Cell phone number incorrectly formatted or does not contain an international code. Please correct the number and try again.\n", secondMessage.checkRecipientCell(secondMessage.getRecipientCell()));
        assertNotEquals("Cell phone number successfully captured.\n", secondMessage.checkRecipientCell(secondMessage.getRecipientCell()));

    }

    @Test
    public void checkMessageHash() {
        // not sure what loop test the requirement was referring to, we only have 2 messages and their Hashes are autogenerated as per another requirement...
        assertEquals("00:0:HITONIGHT", firstMessage.messageHash);
        assertNotEquals("00:1:HITONIGHT", firstMessage.messageHash);
        assertEquals("00:1:HITONIGHT", secondMessage.messageHash);
        assertNotEquals("00:0:HITONIGHT", secondMessage.messageHash);

    }

    @Test
    public void checkMessageBody() {
        assertTrue(firstMessage.checkMessageBody(firstMessage.getMessageBody()));
        assertFalse(firstMessage.checkMessageBody(firstMessage.getMessageBody()));
        assertTrue(secondMessage.checkMessageBody(secondMessage.getMessageBody()));
        assertFalse(secondMessage.checkMessageBody(secondMessage.getMessageBody()));
        // more than 250 characters...
        assertFalse(firstMessage.checkMessageBody("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
    }

    @Test
    public void checkSendMessage() {

    }

}
